apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
  name: astroshop-gateway
  labels:
    configuration: astroshop-gateway
spec:
  contentType: ""
  measurementInterval: 1m
  sources:
    - name: astroshop-otlp-source
  destinations:
    - name: astroshop-otlp-export
  selector:
    matchLabels:
      configuration: astroshop-gateway
